### ISSUE TITLE
Transformar a propriedade address da entidade Company em um tipo complexo

### ISSUE THREAD

**Issue by davidalencar** [SimplesJustica/SimplesJustica.Web#1]
Visando otimização de organização dos dados e flexibilidade para desenrolar de novas atividades.

Novo tipo deve contemplar:
Rua;
Num;
Complemento;
Bairro;
Cidade;
Estado;
País;
CEP;

**Comment by guisfits** [comment]
Novo tipo adicionado a model de company!
