### ISSUE TITLE
Configuração de acesso a banco de dados

### ISSUE THREAD

**Issue by davidalencar** [SimplesJustica/SimplesJustica.Web#2]
Desvincular as cadeias de configuração de acesso do código.

**Comment by guisfits** [comment]
Tem sugestão de onde devemos por ?

**Comment by davidalencar** [comment]
Para resolver esse problema foi criando um arquivo de configuração, semelhante a um web.config, no formato .json e uma rotina que recupera as informações configuradas nele.
Também alterei o .gitignore para não rastrearmos esse arquivo, assim podemos manter nossas informações de conexão ao banco de dados mais seguras.

veja o commit 8fdad77d80aee4537cd3ee0a193fe0851e614bac
